COPY_GOOGLE_DOC_KEY = '1Svi1KWJhW1STHrYszjH5QVVSq-5GmSo9xuod6SYWoeE'
DEPLOY_SLUG = 'vr'
NUM_SLIDES_AFTER_CONTENT = 2

# Configuration
AUDIO = False
VIDEO = False
FILMSTRIP = False
PROGRESS_BAR = False