COPY_GOOGLE_DOC_KEY = '0AlXMOHKxzQVRdHZuX1UycXplRlBfLVB0UVNldHJYZmc'

# post metadata
PROMO_PHOTO = ''
TAGS = []
CAPTION = ''

"""
DO NOT EDIT THESE

DO. NOT. EDIT. THESE.
"""

ID = '$NEW_POST_ID'
IS_PUBLISHED = False