COPY_GOOGLE_DOC_KEY = '0AqjLQISCZzBkdGdxRXdtVDNDMzIwNmN3S2RQd196NUE'
DEPLOY_SLUG = 'test-progress'
NUM_SLIDES_AFTER_CONTENT = 2

# Configuration
AUDIO = False
VIDEO = False
FILMSTRIP = False
PROGRESS_BAR = True